### ISSUE TITLE
Set up basic project structure and development environment (2 SP)

### ISSUE THREAD

**Issue by im-rindu** [DTI-Purwadhika/eventhop-be#2]
### Initialize backend with Spring Boot

- [x] Set up a new Spring Boot project
- [x] Configure dependencies (Spring Web, Spring Data JPA, Supabase client)
- [x] Connect Spring Boot application to Supabase for database management
- [x] Ensure project builds and runs correctly locally

**Comment by im-rindu** [comment]
Om @ripisopol , kita pakai supabase aja yak..
coba kirim emailnya, biar di invite

**Comment by ripisopol** [comment]
ripisopol@gmail.com buat supabase

**Comment by im-rindu** [comment]
ok, nanti saya invite
