### ISSUE TITLE
User Authentication and Authorization  (4 SP)

### ISSUE THREAD

**Issue by im-rindu** [DTI-Purwadhika/eventhop-be#3]
### User Entity

- [ ] kalo ganti apa apa ngomong

**Comment by ripisopol** [comment]
register /api/v1/users/register
login /api/v1/auth/login

working on:
role handling
try email verif(?)
forgot/ reset password
logout

**Comment by im-rindu** [comment]
### Get User List
Requirement:
- Get to retrieve list all of user

Url Path:
`{{base_url}}/api/users?role=[role]&limit=[limit]&page=[page]`
role = Admin | User, Jika kosong all role
limit = jumlah user per page
page = halaman page

Expected Response:
```
{
    "status": 200,
    "message": "OK",
    "messageDetail": "Retrieve 20 from 200 user, Page 1 from 10 page. ",
    "data": [
        {
            "code": "USR-001",
            "username": "budi_setiawan",
            "email": "budi@gmail.com",
            "name": "Budi Setiawan"
        },
        {
            "code": "USR-002",
            "username": "sri_sariawan",
            "email": "sri@gmail.com",
            "name": "Sri Sariawan"
        },
        {
            "code": "USR-003",
            "username": "toto_risoto",
            "email": "toto@gmail.com",
            "name": "Toto Risoto"
        }
    ]
}
```

Expected Failed Response:
```
{
    "status": 400,
    "message": "BAD REQUEST",
    "messageDetail": "Reason of fail",
    "data": []
}
```

**Comment by im-rindu** [comment]
### Get User Detail
Requirement:
- Get to retrieve detail of user

Url Path:
`{{base_url}}/api/v1/users/:id`
:id = id user

Expected Response:
```
{
    "status": 200,
    "message": "OK",
    "messageDetail": "Retrieve User detail of [username]",
    "data": 
    {
        "code": "USR-001",
        "username": "budi_setiawan",
        "email": "budi@gmail.com",
        "name": "Budi Setiawan",
        "photo": "http://localhost:3000/uploads/user-photos/budi_setiawan.jpg",
        "location": "Semarang",
        "role": "admin"
    }
}
```

Expected Failed Response:
```
{
    "status": 400 / 404,
    "message": "BAD REQUEST / NOT FOUND",
    "messageDetail": "Reason of fail",
    "data": []
}
```

**Comment by im-rindu** [comment]
### Update User
Requirement:
- User dapat mengupdate data mereka
- Code, role non-editable
- Username mau dibikin editable atau non-editable? 
- Password tidak boleh di edit disini, password id edit di bagian lain
- email tidak boleh di edit disini, email di edit di bagian lain


Url Path: (PUT)
`{{base_url}}/api/v1/users/:id`
:id = id user

Body Request:
```
{
        "name": "Budi Setiawan",
        "photo": "http://localhost:3000/uploads/user-photos/budi_setiawan.jpg",
        "location": "Semarang",
    }
```

Expected Response:
```
{
    "status": 200,
    "message": "OK",
    "messageDetail": "Updated User detail of [username]",
    "data": 
    {
        "code": "USR-001",
        "username": "budi_setiawan",
        "email": "budi@gmail.com",
        "name": "Budi Setiawan",
        "photo": "http://localhost:3000/uploads/user-photos/budi_setiawan.jpg",
        "location": "Semarang",
        "role": "admin"
    }
}
```

Expected Failed Response:
```
{
    "status": 400 / 404,
    "message": "BAD REQUEST / NOT FOUND",
    "messageDetail": "Reason of fail",
    "data": []
}
```

**Comment by im-rindu** [comment]
### Delete User

Requirement:

- User dapat menutup akun dia sendiri
- Admin dapat menutup akun user
- Jangan beneran dihapus, gunakan soft-delete

Url Path: (DELETE)
```{{base_url}}/api/v1/user/:id```
:id adalah id user


Expected Response: 
```
{
    "status": 204 ,
    "message": "NO CONTENT",
    "messageDetail": "User with [username] closed successfuly",
    "data":[
   {
            "id": 1,
"code": "USR-001",
            "username": "budi_setiawan",
            "email": "budi@gmail.com",
            "name": "Budi Setiawan"
        },
]
}
```

Expected Failed Response: 
```
{
    "status": 400,
    "message": "Bad Request",
    "messageDetail": "Reason of failed",
    "data":[]
}
```

**Comment by im-rindu** [comment]
engga ngaruh juga, lagipula yang dikirim dari frontend ke backend masih sama
email & password, dari backend return jwt

malah dihapus

**Comment by im-rindu** [comment]
masih ikutin requirement ini engga brubah
https://github.com/DTI-Purwadhika/eventhop-be/issues/1#issuecomment-2171298232

requirement sederhana 2 week ago, dan belum ditambah fitur tambahan yang lebih rumit, karena fitur sederhana belum beres
